dashboard/urls.py
from django.urls import path


from .views import (
    dashboard,
    profile,
    messages,
    projects,

    )

app_name = 'dashboard'
urlpatterns = [

    path('', dashboard, name='dashboard'),

    path('messages/', messages, name='messages'),

    path('projects', projects, name='projects'),


]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    homePage,
    projectsPage,
    projectDetail,
    search,
    handler404,
)

from django.conf import settings
from django.conf.urls.static import static


handler404 = handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homePage, name='homePage'),
    path('projects/', projectsPage, name='projectsPage'),
    path('projects/<str:slug>/', projectDetail, name='projectDetail'),
    path('search/', search, name='search'),

    path('dashboard/', include('dashboard.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

dashboard/forms.py
from django import forms
from info.models import Information, Project



class EditProfileForm(forms.ModelForm):
	
	class Meta:
		model = Information
		exclude = ('born_date', 'address', 'cv')

class CreateProjectForm(forms.ModelForm):

	class Meta:
		model = Project
		exclude = ('Slug',)

dashboard/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from info.models import Information, Message, Project




@login_required()
def dashboard(request):
    template_name = 'dashboard.html'
    profile = Information.objects.first()
    return render(request, template_name, {'profile':profile, 'dashboard': True})


@login_required()
def profile(request):
    template_name = 'profile.html'
    context = {}
    profile = Information.objects.first()
    context.update({'profile_active': True, 'profile': profile})
    return render(request, template_name, context)



@login_required()
def messages(request):
    template_name = 'messages.html'
    context = {}
    profile = Information.objects.first()
    messages = Message.objects.all().order_by('-send_time')

    page = request.GET.get('page', 1)

    paginator = Paginator(messages, 6)

    try:
        messages = paginator.page(page)
    except PageNotAnInteger:
        messages = paginator.page(1)
    except EmptyPage:
        messages = paginator.page(paginator.num_pages)

    context.update({'messages_active': True, 'messages': messages, 'profile': profile})
    return render(request, template_name, context)


@login_required()
def projects(request):
    template_name = 'dashboard_projects.html'
    context = {}
    profile = Information.objects.first()
    projects = Project.objects.all().order_by('-id')
    context.update({'projects_active': True, 'projects': projects, 'profile': profile})
    return render(request, template_name, context)

dashboard/templates/dash_navbar.html
<!-- Topbar -->{% load static %}
    <nav class="navbar navbar-expand topbar mb-4 static-top shadow dash-navbar">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search -->
        <div class="title">
            <h1 class="h4  text-gray-800">Elhadj Mamadou Diallo</h1>
        </div>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle message-icon" href="#" id="messagesDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-envelope fa-fw"></i>
                    <!-- Counter - Messages -->
                    <span class="badge badge-danger badge-counter">7</span>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                    aria-labelledby="messagesDropdown">
                    <div class="massage-header py-3 text-center">Messages Counter</div>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="{% static 'img/message.svg' %}"
                                alt="">
                        </div>
                        <div class="font-weight-bold">
                            <div class="text-truncate">Hi there! I am wondering if you can help me with a
                                problem I've been having.</div>
                            <div class="small text-gray-500">Emily Fowler</div>
                        </div>
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="#">
                        <div class="dropdown-list-image mr-3">
                            <img class="rounded-circle" src="{% static 'img/message.svg' %}"
                                alt="">
                        </div>
                        <div class="font-weight-bold">
                            <div class="text-truncate">Hi there! I am wondering if you can help me with a
                                problem I've been having.</div>
                            <div class="small text-gray-500">Emily Fowler</div>
                        </div>
                    </a>

                    <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">Elhadj Mamadou Diallo</span>
                    <img class="img-profile rounded-circle"
                        src="{% if user.avatar %}{{user.avatar.url}}{% else %}{% static 'img/default-avatar.svg' %}{% endif %}">
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                    aria-labelledby="userDropdown">
                    <a class="dropdown-item user-dropdown" href="#">
                        <i class="fas fa-user mr-2"></i>
                        Profile
                    </a>
                    <a class="dropdown-item user-dropdown" href="/">
                        <i class="fas fa-eye mr-2"></i>
                        <span>View Site</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item user-logout" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt mr-2"></i>
                        Logout
                    </a>
                </div>
            </li>

        </ul>

</nav>
    <!-- End of Topbar -->

dashboard/templates/dash_sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav sidebar dash_sidebar" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    
    <a class="sidebar-brand d-flex align-items-center justify-content-center">
        <div class="sidebar-brand-icon text-white">
            <i class="fas fa-tachometer-alt"></i>
        </div>
        <div class="sidebar-brand-text dash-icon">Dashboard</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Information
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item my-1">
        <a class="{% if profile_active %}link-active{% endif %}" href="{% url 'dashboard:profile' %}">
            <i class="fas fa-cog"></i>
            <span>Profile</span>
        </a>
    </li>
    <li class="nav-item mb-1">
        <a class="{% if messages_active %}link-active{% endif %}" href="{% url 'dashboard:messages' %}">
            <i class="fas fa-envelope"></i>
            <span>Messages</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider mt-2">

    <!-- Heading -->
    <div class="sidebar-heading">
        Addons
    </div>

    <!-- Nav Item - Charts -->
    <li class="nav-item mt-1">
        <a class="" href="charts.html">
            <i class="fas fa-chart-area"></i>
            <span>Projects</span></a>
    </li>
    <li class="nav-item mt-1">
        <a class="" href="charts.html">
            <i class="ni ni-atom"></i>
            <span>Competences</span></a>
    </li>

    <li class="nav-item mt-1">
        <a class="" href="charts.html">
            <i class="ni ni-hat-3"></i>
            <span>Educations</span></a>
    </li>

    <li class="nav-item my-1">
        <a class="" href="charts.html">
            <i class="ni ni-archive-2"></i>
            <span>Experiences</span></a>
    </li>
</ul>
<!-- End of Sidebar -->

dashboard/templates/dashboard.html
{% extends 'base.html' %}

{% load static %}
{% block style %}
    <link type="text/css" href="{% static 'dashboard.css' %}" rel="stylesheet">
{% endblock style %}

{% block body %}

<div class="container mt-lg-8">
    <div class="row">
        <div class="col-lg-4 sidebar p-0">
            <a href="{% url 'dashboard:dashboard' %}">
                <div class="row info {% if dashboard %}dashboard-active {% else %}info-unactive{% endif %}">
                    <div class="col-2 pic">
                        <div class="profile-pic shadow" style="background-image: url('{% if profile.avatar %}{{profile.avatar.url}}{% else %}{% static 'img/default-avatar.svg' %}{% endif %}')">
                        </div>
                    </div>
                    <div class="col-10 name">
                        <h5 class="full-name">{{profile.name_complete}}</h5>
                        <p class="email">{{profile.email}}</p>
                    </div>
                </div>
            <a/>
            <hr class="m-0 mb-1">
            <ul class="sidebar-list">
                <a href="{% url 'dashboard:profile' %}">
                    <li class="{% if profile_active %}link-active{% endif %}">
                        {% comment %} <img src="{% static 'img/profile.svg' %}" width='25px'> {% endcomment %}
                        <i class="uil uil-user dashboard-icon"></i>
                        Profile
                    </li>
                </a>
                <a href="{% url 'dashboard:messages' %}">
                    <li class="{% if messages_active %}link-active{% endif %}">
                        {% comment %} <img src="{% static 'img/messages.svg' %}" width='25px'> {% endcomment %}
                        <i class="uil uil-envelope-download dashboard-icon"></i>
                        Messages
                    </li>
                </a>
                <hr class="sidebar-line">
                <a href="{% url 'dashboard:education' %}">
                    <li>
                        {% comment %} <img src="{% static 'img/education.svg' %}" width='28px'> {% endcomment %}
                        <i class="uil uil-graduation-cap dashboard-icon"></i>
                        Educations
                    </li>
                </a>
                <a href="{% url 'dashboard:profile' %}">
                    <li>
                        {% comment %} <img src="{% static 'img/competences.svg' %}" width='28px'> {% endcomment %}
                        <i class="uil uil-award dashboard-icon"></i>
                        Competences
                    </li>
                </a>
                <a href="{% url 'dashboard:profile' %}">
                    <li>
                        {% comment %} <img src="{% static 'img/experiences.svg' %}" width='25px'> {% endcomment %}
                        <i class="uil uil-spinner-alt dashboard-icon"></i>
                        Experiences
                    </li>
                </a>
                <a href="{% url 'dashboard:projects' %}">
                    <li class="{% if projects_active %}link-active{% endif %}">
                        {% comment %} <img src="{% static 'img/dash-projects.svg' %}" width='25px'> {% endcomment %}
                        <i class="uil uil-folder-open dashboard-icon"></i>
                        Projects
                    </li>
                </a>
            </ul>
            <hr class="sidebar-line">
            <div class="container text-center sidebar-footer">
                <a href="{% url 'homePage' %}">
                    <img class="svg-icon-home" src="{% static 'img/home-icon.svg' %}" width='20px'>
                    Home
                </a>
                <a href="{% url 'dashboard:logout' %}" id="logout">
                    <img class="svg-icon-logout" src="{% static 'img/logout-icon.svg' %}" width='20px'>
                    Logout
                </a>
            </div>
        </div>
        <div class="col-lg-8 dashboard-content pl-lg-4">
            {% block dashboardContent %}
                <div class="dashboard-title">Dashboard</div>
                <div class=""><small>Welcome Again</small></div>
                <div class="row">
                    <div class="col-12 card">
                        <div class="">
                            <div class="">
                                <div class="">
                                    Welcome Again
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            {% endblock dashboardContent %}
        </div>
    </div>
</div>

<div class="container dash-footer my-6 py-2">
    <div class="text-center">
        <p>Copyright © {% now "Y" %} Elhadj Mamadou Diallo . All rights reserved</p>
        <p class="coder">Built with <i class="fa fa-heart text-danger"></i> in Django By <a href="https://github.com/abdlalisalmi">Elhadj Mamadou Diallo</a></p>
    </div>
</div>


{% endblock body %}



{% block script %}
    <script src="{% static 'dashboard.js' %}"></script>
{% endblock script %}

dashboard/templates/dashboard_education.html
{% extends 'dashboard.html' %}

{% load static %}

{% block dashboardContent %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="dashboard-title">Education</div>
            <small>Manage your education</small>
        </div>
        
        <div class="col-6">
            <div class="create-one" id="display-create-form">
                Create One
            </div>
        </div>
    </div>
    <hr class="mt-2">


    <div class="create-project-form hide">
        <form>
            <div class="form-group">
                <lable>Title</lable>
                <input type="text" class="form-control" id="form-title" placeholder="Education title">
            </div>
            <div class="form-group">
                <lable>Description</lable>
                <textarea class="form-control" id="form-description" rows="10" placeholder="Education description"></textarea>
            </div>
            <div class="form-group">
                <lable>Date</lable>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="uil uil-calendar-alt"></i></span>
                    </div>
                    <input type="text" class="form-control" id="form-date" placeholder="Education year">
                </div>
            </div>
        </form>
        <div class="modal-footer">
            <a class="submit-project" id="creat-project-btn">
                <img src="{% static 'img/save-icon.svg' %}" width='25px'>
                Save
            </a>
            <a class="submit-project" id="submit-update-project">
                <img src="{% static 'img/edit-icon.svg' %}" width='25px'>
                Update
            </a>

            <a class="cancel-edit-project" id="display-create-form">
                <img src="{% static 'img/close-icon.svg' %}" width='25px'>
                Close
            </a>
        </div>

    </div>

    <div class="row">
        {% comment %} <div class="ml-3 mt-4 h5">Projects</div> {% endcomment %}
        <div class="col-12 dashboard-projects-list">
            {% for edu in education %}
                <div class="row item">
                    <div class="col-3 item-name">
                        {{edu.title|truncatechars:15}}
                    </div>
                    <div class="col-6  text-muted text-left">
                        {{edu.description|truncatechars:38}}
                    </div>
                    <div class="col-3 text-right">
                        <i class="uil uil-edit-alt icon-edit"></i>
                        <i class="uil uil-trash-alt icon-delete"></i>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    
</div>

{% endblock dashboardContent %}

dashboard/templates/dashboard_projects.html
{% extends 'dashboard.html' %}

{% load static %}

{% block dashboardContent %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="dashboard-title">Projects</div>
            <small>Manage your projects</small>
        </div>
        
        <div class="col-6">
            <div class="create-one" id="display-create-form">
                Create One
            </div>
        </div>
    </div>
    <hr class="mt-2">


    <div class="create-project-form hide">
        <form>
            <div class="form-group">
                <lable>Title</lable>
                <input type="text" class="form-control" id="form-title" placeholder="Project title">
            </div>
            <div class="form-group">
                <lable>Description</lable>
                <textarea class="form-control" id="form-description" rows="10" placeholder="Project description"></textarea>
            </div>
            <div class="form-group">
                <lable>Image</lable>
                <input type="file" class="form-control" id="form-image">
            </div>
            <div class="form-group">
                <lable>Tools</lable>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-cog"></i></i></span>
                    </div>
                    <input type="text" class="form-control" id="form-tools" placeholder="Project building tools">
                </div>
            </div>

            <div class="form-group">
                <lable>Demo</lable>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-globe"></i></span>
                    </div>
                    <input type="text" class="form-control" id="form-demo" placeholder="Project web site">
                </div>
            </div>

            <div class="form-group">
                <lable>Github</lable>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fab fa-github"></i></span>
                    </div>
                    <input type="text" class="form-control" id="form-github" placeholder="Github repository">
                </div>
            </div>

            <lable>Home Display</lable>
            <div class="form-group">
                <div class="custom-control custom-checkbox mb-3">
                    <input class="custom-control-input" id="form-show_in_slider" type="checkbox">
                    <label class="custom-control-label" for="form-show_in_slider">Checked</label>
                </div>
            </div>
            <input type="hidden" id="project-id">
        </form>
        <div class="modal-footer">
            <a class="submit-project" id="creat-project-btn">
                <img src="{% static 'img/save-icon.svg' %}" width='25px'>
                Save
            </a>
            <a class="submit-project" id="submit-update-project">
                <img src="{% static 'img/edit-icon.svg' %}" width='25px'>
                Update
            </a>

            <a class="cancel-edit-project" id="display-create-form">
                <img src="{% static 'img/close-icon.svg' %}" width='25px'>
                Close
            </a>
        </div>

    </div>

    {% comment %} {% with projects|first as project %}
        <div class="row" id="one-project">
            <div class="col-12 one-project">
                <div class="content">
                    <img src="{{project.image.url}}">
                    <div class="">
                        <h3>{{project.title|truncatechars:30}}</h3>
                        <p>{{project.description|safe|truncatechars:140}}</p>
                        <a href="{{project.get_project_absolute_url}}">
                            <div class="link">
                                Show the project
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endwith %} {% endcomment %}


    
    <div class="row">
        {% comment %} <div class="ml-3 mt-4 h5">Projects</div> {% endcomment %}
        <div class="col-12 dashboard-projects-list">
            {% for project in projects %}
                <div class="row item">
                    <div class="col-8 item-name">
                        <a href="{{project.get_project_absolute_url}}" class="text-black" target="_blank">
                            {{project.title|truncatechars:40}}
                        </a>
                    </div>
                    <div class="col-4 text-right">
                        <img class="svg-icon-edit" src="{% static 'img/edit-icon.svg' %}" width='20px' id="{{project.id}}">
                        <img class="svg-icon-delete" src="{% static 'img/trash-icon.svg' %}" width='20px' id="{{project.id}}">
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    
</div>

{% endblock dashboardContent %}

dashboard/templates/messages.html
{% extends 'dashboard.html' %}

{% load static %}

{% block dashboardContent %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 inbox">
            <i class="fas fa-inbox"></i>
            Inbox 
        </div>
        <div class="col-lg-6 search">
            <div class="form-group">
                <div class="input-group mb-4">
                    <input class="form-control" id="search-input" placeholder="Search for messages" type="text">
                    <div class="search-btn" id="search-btn">
                        <i class="fa fa-search"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr class="mt-0">

    {% for message in messages %}
        <div class="row message-item {% if not message.is_read %}new-message{% endif %}" id="row-{{message.id}}">
            <div class="col-1 message-icons">
                <div class="delete-message" id="message-{{message.id}}">
                    <img src="{% static 'img/trash-icon.svg' %}" width='25px'>
                </div>
            </div>
            <div class="col-9 view-message" id="view-{{message.id}}" data-toggle="modal" data-target=".modal-{{message.id}}">
                <div class="row">
                    <div class="col-3 sender text-capitalize">
                        {{message.name}}
                    </div>
                    <div class="col-9 message">
                        {{message.message|truncatechars:60}}
                    </div>
                </div>
            </div>
            <div class="col-2 time">
                {{message.send_time|date:"D, d M, Y"}}
            </div>
        </div>

        <div class="modal fade modal-{{message.id}}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="message-modal">
                    <div class="modal-head text-capitalize">
                        {{message.name}}
                    </div>
                    <div class="modal-body">
                        {{message.message}}
                        <p><i class="fas fa-envelope"></i> {{message.email}}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <nav aria-label="Page navigation example ">
        <ul class="pagination justify-content-center mt-3 mb-0">
            <li class="page-item {% if not messages.has_previous %}disabled{% endif %}">
                <a class="page-link pagination-move" href="{% if messages.has_previous %}?page={{ messages.previous_page_number }}{% endif %}" tabindex="-1">
                    <i class="fa fa-angle-left"></i>
                    <span class="sr-only">Previous</span>
                </a>
            </li>

                <li class="page-item pagination-number {% if not messages.has_previous %}disabled{% endif %}">
                    <a class="page-link" href="{% if messages.has_previous %}?page={{ messages.previous_page_number }}{% endif %}">{{messages.number|add:-1}}</a>
                </li>
                <li class="page-item pagination-active">
                    <a class="page-link" href="?page={{ messages.number }}">{{messages.number}}</a>
                </li>
                <li class="page-item pagination-number {% if not messages.has_next %}disabled{% endif %}">
                    <a class="page-link" href="{% if messages.has_next %}?page={{ messages.next_page_number }}{% endif %}">{{messages.number|add:1}}</a>
                </li>

            <li class="page-item {% if not messages.has_next %}disabled{% endif %}">
                <a class="page-link pagination-move" href="{% if messages.has_next %}?page={{ messages.next_page_number }}{% endif %}">
                    <i class="fa fa-angle-right"></i>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    </nav>
    
</div>

{% endblock dashboardContent %}